### PR TITLE
Fix test.

### PR DESCRIPTION
**Pull request by romanb**
The problem with the test is the following: It is publishing to `swarms[31]`, but `swarms[31]` only gets to know about `swarms[0]` to `swarms[29]`. `swarms[31]` does a `FIND_NODE` before the `PUT_VALUE`, but that won't make it discover `swarms[30]`, because all the `FIND_NODE` replies will have an empty list of closer peers. And that is because when receiving a `PUT_VALUE`,  while the receiver adds the sender to its k-buckets, it apparently has no address for it (https://github.com/libp2p/rust-libp2p/blob/master/protocols/kad/src/behaviour.rs#L504-L507). That may be a separate issue, but I suggest to just make your test simpler, as mentioned in the PR comments. A separate mistake in the expectations of the test is that they expect 21 peers in `have_key` but that should be 20 because you are (on purpose) excluding `swarm[31]`, the publisher, from the swarms you issue a `get_value` on.

### CODE REVIEW

**Comment by romanb** [comment]
Actually, I think I misunderstood the original test setup and am still wrapping my head around it, but at least there is a variant of the test that works now, if that helps.

**Comment by montekki** [comment]
Ok, the idea of the test is following:

I am trying to test that a PUT_VALUE will correctly propagate to the nodes in the network not only in the case when we are connected to everyone else. This setup is following

```
[31] -> [30]
        /  | \ 
    [29] ....... [0]
```

So we need to corretly collet the peers that are the closest to the key and what happens is:

`[31]` starts with knowing only about one `id` closest to the `key`: that being `[30]`, so it asks it for closest. By this point `[30]` is the only node in `closest_peers`.

`[30]` receives the `FindNode` query and returns 20 closest peers out of 30 peers he knows of, they get returned to `[31]`.

`[31]` starts merging the received list with his own, which is at this point still only `[31]` and starting the queries to them with `QueryPeerState::NotContacted` (this all happens in the `inject_rpc_result`)

At some point when `poll()` is called we have enough of those queries that are finished (the `if succeeded_counter >= num_results {` branch in `poll()`) and we return them, But the problem here is that sometimes those finished queries are not the closest ones (some query in the middle of the list might still not have reached the `QueryPeerState::Succeeded` state) so what we return is not "the closest peers" but rather "the peers, queries to which have succeeded first" which brings the randomness to test fails.

Now, getting back to your proposed patch it works always b.c. it doesn't seem to trigger this behaviour. Indeed: We are connected to 31 nodes, all of those nodes are connected to noone. So we start with a set of closest peers equals to 31, and they return no results to be merged inside the `inject_rpc_result`.

**Comment by romanb** [comment]
I updated the PR based on the original test you had. It incorporates the latest changes from master and https://github.com/montekki/rust-libp2p/pull/1/commits/544dfa4393c1be026ed7d426ed111d64b88dd88a. This addresses all three issues that the test had:

  1. The bug in `query.rs` regarding premature termination.
  2. Avoiding bucket overflow by altering the topology of the swarms in the test.
  3. Not using `get_value` but rather only check the local storage of each swarm after `PUT_VALUE`.

Just in case you are still interested in this test, which I think is valuable although it should still be cleaned up a bit. I can submit the fix for `query.rs` as a separate PR to libp2p, if you want to integrate these changes.

**Comment by romanb** [comment]
Closing since https://github.com/libp2p/rust-libp2p/pull/1155 has been merged and the other issues have been resolved already.

**Pull request closed without merging**
